import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers";
import { AppBar } from "@/components/appBar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import AppSidebar from "@/components/app-sidebar";
import { Toaster } from "sonner";
import Footer from "@/components/footer";
// import { Toaster } from "@/components/ui/toaster";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Providers>
                    <div className="flex flex-col h-screen">

                        <div style={{ display: "flex", flexDirection: "row", alignItems: "center" }}>
                            <AppBar />
                        </div>

                        <div className="flex-1">
                            <AppSidebar />

                            <div className="flex flex-col ">
                                <main className="flex-grow">

                                    {children}

                                    <Toaster/>

                                </main>
                            </div>
                        </div>

                        <Footer />

                    </div>
                </Providers>
                <Toaster />
            </body>
        </html>
    );

}
