# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: roman.njoroge@njuguna.com
author_name: romannjoroge
contract_name: poma
deployment_language: python
preset_name: starter
project_name: contract

